### ISSUE TITLE
Build fails on macOS 10.14.6

### ISSUE THREAD

**Issue by termhn** [EmbarkStudios/rust-gpu#123]
### Expected Behaviour

example-runner builds and runs

### Example & Steps To Reproduce

1. follow startup guide
2. `cargo run --bin example-runner`
3. build fails

## System Info

 - Rust: rustc 1.49.0-nightly (a9cd294cf 2020-10-22)
 - OS: macOS 10.14.6
 - GPU: Intel Iris (?)
 - SPIR-V: SPIRV-Tools v2020.6 v2020.5-80-gabe2eff3

## Backtrace

<details><summary>Backtrace</summary>
<p>

```
~/C/rust-gpu ❯❯❯ RUST_BACKTRACE=1 cargo run --bin example-runner         ✘ 101
   Compiling ash-molten v0.6.0+43 (https://github.com/EmbarkStudios/ash-molten?branch=moltenvk-1.1.0#d0cb9e55)
   Compiling example-runner v0.1.0 (/Users/gray/Code/rust-gpu/examples/example-runner)
error: failed to run custom build command for `ash-molten v0.6.0+43 (https://github.com/EmbarkStudios/ash-molten?branch=moltenvk-1.1.0#d0cb9e55)`

Caused by:
  process didn't exit successfully: `/Users/gray/Code/rust-gpu/target/debug/build/ash-molten-47b38550fede2767/build-script-build` (exit code: 101)
  --- stdout
  Already up to date.

  ========== Retrieving MoltenVK dependencies into External ==========

  ========== Cereal ==========

  cereal repo: https://github.com/USCiLab/cereal.git
  cereal revision: 51cbda5f30e56c801c07fe3d3aba5d7fb9e6cca4
  Fetching origin

  ========== Vulkan-Headers ==========

  Vulkan-Headers repo: https://github.com/KhronosGroup/Vulkan-Headers.git
  Vulkan-Headers revision: 7f9879b1b1fab53f719a9ed5e6e29533b10972b2
  Fetching origin

  ========== SPIRV-Cross ==========

  SPIRV-Cross repo: https://github.com/KhronosGroup/SPIRV-Cross.git
  SPIRV-Cross revision: e6f5ce6b8998f551f3400ad743b77be51bbe3019
  Fetching origin

  ========== glslang and SPIRV-Tools ==========

  glslang repo: https://github.com/KhronosGroup/glslang.git
  glslang revision: bacaef3237c515e40d1a24722be48c0a0b30f75f
  Fetching origin
  0a1fb588cd365f7737cb121fdd64553923e0cef6
  060627f0b0d2fa8581b5acb939f46e3b9e500593
  Change directory to .
  Get spirv-tools

  In External/spirv-tools: ['git', 'remote']
  known-good
  origin

  In External/spirv-tools: ['git', 'checkout', u'0a1fb588cd365f7737cb121fdd64553923e0cef6']

  Get spirv-tools/external/spirv-headers

  In External/spirv-tools/external/spirv-headers: ['git', 'remote']
  known-good
  origin

  In External/spirv-tools/external/spirv-headers: ['git', 'checkout', u'060627f0b0d2fa8581b5acb939f46e3b9e500593']


  ========== Vulkan-Tools ==========

  Vulkan-Tools repo: https://github.com/KhronosGroup/Vulkan-Tools.git
  Vulkan-Tools revision: 2bfd6a752dc6cb26ceda4ec9d56e7dce98527680
  Fetching origin

  ========== VulkanSamples ==========

  VulkanSamples repo: https://github.com/LunarG/VulkanSamples.git
  VulkanSamples revision: a1fe1176690ec2574deb4dd3be6c4e62d1f5d186
  Fetching origin

  ========== Started building dependency libraries at 12:55:48 PM ==========
  Please be patient on first build
  Building external libraries for macOS
  still building MoltenVK
  still building MoltenVK
  still building MoltenVK
  still building MoltenVK
  still building MoltenVK
  still building MoltenVK
  still building MoltenVK
  still building MoltenVK
  still building MoltenVK
  still building MoltenVK
  still building MoltenVK
  still building MoltenVK
  still building MoltenVK
  still building MoltenVK
  Completed building external libraries for macOS
  xcframework successfully written out to: /Users/gray/Code/rust-gpu/target/debug/build/ash-molten-86dfc2a28855154e/out/MoltenVK-v1.1.0/External/build/Release/SPIRVCross.xcframework
  xcframework successfully written out to: /Users/gray/Code/rust-gpu/target/debug/build/ash-molten-86dfc2a28855154e/out/MoltenVK-v1.1.0/External/build/Release/SPIRVTools.xcframework
  xcframework successfully written out to: /Users/gray/Code/rust-gpu/target/debug/build/ash-molten-86dfc2a28855154e/out/MoltenVK-v1.1.0/External/build/Release/glslang.xcframework
  ========== Finished at 01:03:13 PM ==========
  xcodebuild build -quiet -project "MoltenVKPackaging.xcodeproj" -scheme "MoltenVK Package (macOS only)"
  still building MoltenVK
  still building MoltenVK
  /Users/gray/Code/rust-gpu/target/debug/build/ash-molten-86dfc2a28855154e/out/MoltenVK-v1.1.0/MoltenVK/MoltenVK/GPUObjects/MVKImage.mm:1283:42: warning: undeclared selector 'addPresentedHandler:' [-Wundeclared-selector]
                  if ([_mtlDrawable respondsToSelector: @selector(addPresentedHandler:)]) {
                                                         ^
  /Users/gray/Code/rust-gpu/target/debug/build/ash-molten-86dfc2a28855154e/out/MoltenVK-v1.1.0/MoltenVK/MoltenVK/GPUObjects/MVKImage.mm:1287:52: error: property 'presentedTime' not found on object of type 'id<MTLDrawable>'
                                  CFTimeInterval presentedTimeSeconds = drawable.presentedTime;
                                                                                 ^
  /Users/gray/Code/rust-gpu/target/debug/build/ash-molten-86dfc2a28855154e/out/MoltenVK-v1.1.0/MoltenVK/MoltenVK/GPUObjects/MVKImage.mm:1285:18: warning: instance method '-addPresentedHandler:' not found (return type defaults to 'id') [-Wobjc-method-access]
                          [_mtlDrawable addPresentedHandler: ^(id<MTLDrawable> drawable) {
                                        ^~~~~~~~~~~~~~~~~~~
  2 warnings and 1 error generated.
  note: Using new build system
  note: Planning build
  note: Constructing build description

  --- stderr
  HEAD is now at 51cbda5f Merge branch 'develop' for release 1.2.2
  HEAD is now at 7f9879b Update for Vulkan-Docs 1.2.154
  HEAD is now at e6f5ce6b Merge pull request #1471 from KhronosGroup/fix-1467
  HEAD is now at bacaef32 Update spirv-tools and spirv-headers known goods (#2401)
  HEAD is now at 0a1fb588 Update CHANGES
  HEAD is now at 060627f Register the ANGLE compiler (#168)
  HEAD is now at 2bfd6a75 vulkaninfo: Add json output for portability subset
  HEAD is now at a1fe11766 Update to 1.2.154 headers
  ** BUILD FAILED **

  make: *** [macos] Error 65
  thread 'main' panicked at 'failed to fetchDependencies', /Users/gray/.cargo/git/checkouts/ash-molten-2e22393c7b19b606/d0cb9e5/build.rs:107:9
  stack backtrace:
     0: std::panicking::begin_panic
               at /Users/gray/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/panicking.rs:505:12
     1: build_script_build::mac::build_molten
               at ./build.rs:107:9
     2: build_script_build::main
               at ./build.rs:148:27
     3: core::ops::function::FnOnce::call_once
               at /Users/gray/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</p>
</details>

**Comment by khyperia** [comment]
wait, should this be reported in ash-molten instead of here? or are you just posting this here as a tracking item to acknowledge there's a problem?

**Comment by termhn** [comment]
Yeah it should probably be reported on ash-molten but I'll keep here as well to track that it's an issue for building this as well like you say.

**Comment by XAMPPRocky** [comment]
Closing as this seems like it's just an issue with the minimum supported version of macOS being 10.15+, and there's not much we can do here.
