### ISSUE TITLE
wgpu example on Mac results in `unsupported features were requested: SPIRV_SHADER_PASSTHROUGH`

### ISSUE THREAD

**Issue by Cactice** [EmbarkStudios/rust-gpu#853]
### Expected Behaviour

Successfully run the wgpu example on Mac with no error.

### Example & Steps To Reproduce

0. `git clone --recurse-submodules https://github.com/EmbarkStudios/rust-gpu`
1. `cd examples/runners/wgpu`
2. `cargo run ` 
3. Get error `unsupported features were requested: SPIRV_SHADER_PASSTHROUGH`

I used above method because `cargo run --bin example-runner-wgpu`had an issue
```
cargo run --bin example-runner-wgpu
error: no bin target named `example-runner-wgpu`

Did you mean `example-runner-cpu`?
```
I tested on master and the patch branch on this PR https://github.com/EmbarkStudios/rust-gpu/pull/852 but the issue occurred on both branches.

## System Info

 - Rust: [1.60.0-nightly (1bd4fdc94 2022-01-12)]
 - OS: [macOS 12.2.1]
 - GPU: [Intel Iris Graphics 6100 1536 MB]
 - SPIR-V: [None]

## Backtrace

<details><summary>Backtrace</summary>
<p>

```
➜  wgpu git:(patched) ✗ RUST_BACKTRACE=1 cargo run 
    Finished dev [unoptimized + debuginfo] target(s) in 0.20s
     Running `/Users/yuya/git/rust-gpu/target/debug/wgpu_runner`
    Finished release [optimized] target(s) in 0.17s
[2022-03-08T03:47:34Z ERROR wgpu::backend::direct] Error in Adapter::request_device: unsupported features were requested: SPIRV_SHADER_PASSTHROUGH
thread 'main' panicked at 'Failed to create device: RequestDeviceError', examples/runners/wgpu/src/graphics.rs:77:10
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: core::result::Result<T,E>::expect
             at /rustc/1bd4fdc943513e1004f498bbf289279c9784fc6f/library/core/src/result.rs:975:23
   4: example_runner_wgpu::graphics::run::{{closure}}
             at ./src/graphics.rs:67:27
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/1bd4fdc943513e1004f498bbf289279c9784fc6f/library/core/src/future/mod.rs:84:19
   6: futures_executor::local_pool::block_on::{{closure}}
             at /Users/yuya/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.19/src/local_pool.rs:315:23
   7: futures_executor::local_pool::run_executor::{{closure}}
             at /Users/yuya/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.19/src/local_pool.rs:90:37
   8: std::thread::local::LocalKey<T>::try_with
             at /rustc/1bd4fdc943513e1004f498bbf289279c9784fc6f/library/std/src/thread/local.rs:412:16
   9: std::thread::local::LocalKey<T>::with
             at /rustc/1bd4fdc943513e1004f498bbf289279c9784fc6f/library/std/src/thread/local.rs:388:9
  10: futures_executor::local_pool::run_executor
             at /Users/yuya/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.19/src/local_pool.rs:86:5
  11: futures_executor::local_pool::block_on
             at /Users/yuya/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.19/src/local_pool.rs:315:5
  12: example_runner_wgpu::graphics::start
             at ./src/graphics.rs:365:13
  13: example_runner_wgpu::main
             at ./src/lib.rs:167:9
  14: wgpu_runner::main
             at ./src/bin/wgpu_runner.rs:2:5
  15: core::ops::function::FnOnce::call_once
             at /rustc/1bd4fdc943513e1004f498bbf289279c9784fc6f/library/core/src/ops/function.rs:227:5
```

</p>
</details>

**Comment by andrusha** [comment]
You need to install MoltenVK and use this patch which enabled vulkan-compatibility in wgpu https://github.com/EmbarkStudios/rust-gpu/pull/852

**Comment by Cactice** [comment]
I was able to get the sky to show up after installing [Vulkan SDK](https://vulkan.lunarg.com/).
Although there were lots of validation errors.

<details><summary>Backtrace</summary>
<p>

```
[2022-03-11T00:05:14Z ERROR wgpu_hal::vulkan::instance] VALIDATION [VUID-VkShaderModuleCreateInfo-pCode-01091 (0xa7bb8db6)]
        Validation Error: [ VUID-VkShaderModuleCreateInfo-pCode-01091 ] Object 0: handle = 0x7f9c46895c18, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xa7bb8db6 | vkCreateShaderModule(): The SPIR-V Capability (VulkanMemoryModel) was declared, but none of the requirements were met to use it. The Vulkan spec states: If pCode declares any of the capabilities listed in the SPIR-V Environment appendix, one of the corresponding requirements must be satisfied (https://vulkan.lunarg.com/doc/view/1.3.204.1/mac/1.3-extensions/vkspec.html#VUID-VkShaderModuleCreateInfo-pCode-01091)
[2022-03-11T00:05:14Z ERROR wgpu_hal::vulkan::instance]       objects: (type: DEVICE, hndl: 0x7f9c46895c18, name: ?)
[2022-03-11T00:05:14Z ERROR wgpu_hal::vulkan::instance] VALIDATION [VUID-VkShaderModuleCreateInfo-pCode-04147 (0x3d492883)]
        Validation Error: [ VUID-VkShaderModuleCreateInfo-pCode-04147 ] Object 0: handle = 0x7f9c46895c18, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x3d492883 | vkCreateShaderModule(): The SPIR-V Extension (SPV_KHR_vulkan_memory_model) was declared, but none of the requirements were met to use it. The Vulkan spec states: If pCode declares any of the SPIR-V extensions listed in the SPIR-V Environment appendix, one of the corresponding requirements must be satisfied (https://vulkan.lunarg.com/doc/view/1.3.204.1/mac/1.3-extensions/vkspec.html#VUID-VkShaderModuleCreateInfo-pCode-04147)
[2022-03-11T00:05:14Z ERROR wgpu_hal::vulkan::instance]       objects: (type: DEVICE, hndl: 0x7f9c46895c18, name: ?)
[2022-03-11T00:05:14Z ERROR wgpu_hal::vulkan::instance] VALIDATION [VUID-VkShaderModuleCreateInfo-pCode-01091 (0xa7bb8db6)]
        Validation Error: [ VUID-VkShaderModuleCreateInfo-pCode-01091 ] Object 0: handle = 0x7f9c46895c18, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xa7bb8db6 | vkCreateShaderModule(): The SPIR-V Capability (VulkanMemoryModel) was declared, but none of the requirements were met to use it. The Vulkan spec states: If pCode declares any of the capabilities listed in the SPIR-V Environment appendix, one of the corresponding requirements must be satisfied (https://vulkan.lunarg.com/doc/view/1.3.204.1/mac/1.3-extensions/vkspec.html#VUID-VkShaderModuleCreateInfo-pCode-01091)
[2022-03-11T00:05:14Z ERROR wgpu_hal::vulkan::instance]       objects: (type: DEVICE, hndl: 0x7f9c46895c18, name: ?)
[2022-03-11T00:05:14Z ERROR wgpu_hal::vulkan::instance] VALIDATION [VUID-VkShaderModuleCreateInfo-pCode-04147 (0x3d492883)]
        Validation Error: [ VUID-VkShaderModuleCreateInfo-pCode-04147 ] Object 0: handle = 0x7f9c46895c18, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x3d492883 | vkCreateShaderModule(): The SPIR-V Extension (SPV_KHR_vulkan_memory_model) was declared, but none of the requirements were met to use it. The Vulkan spec states: If pCode declares any of the SPIR-V extensions listed in the SPIR-V Environment appendix, one of the corresponding requirements must be satisfied (https://vulkan.lunarg.com/doc/view/1.3.204.1/mac/1.3-extensions/vkspec.html#VUID-VkShaderModuleCreateInfo-pCode-04147)
[2022-03-11T00:05:14Z ERROR wgpu_hal::vulkan::instance]       objects: (type: DEVICE, hndl: 0x7f9c46895c18, name: ?)
```
</p>
</details>
