### ISSUE TITLE
`missing libm intrinsic` error while using `spirv-builder` with `build.rs`

### ISSUE THREAD

**Issue by bits0rcerer** [EmbarkStudios/rust-gpu#938]
### Expected Behaviour

- shader crate compiles successfully

### Example & Steps To Reproduce

1. I followed the [`Writing Shader Crates`](https://embarkstudios.github.io/rust-gpu/book/writing-shader-crates.html#writing-shader-crates) guide and tried the [`hello-compute`](https://github.com/EmbarkStudios/rust-gpu/tree/main/examples/shaders/compute-shader) example
2. my project crate and the shader crate have the same [`rust-toolchain`](https://github.com/EmbarkStudios/rust-gpu/blob/27e3cfc328938b07961a01bc04a309f5f29de4fa/rust-toolchain) file
3. `cargo build`
4. get `error: missing libm intrinsic _RNvNtNtCsdZLD7L8TQMH_4libm4math4rint4rint, which is math::rint::rint`

##### build.rs:

```rust
use spirv_builder::{MetadataPrintout, SpirvBuilder};

fn main() {
    match SpirvBuilder::new("shaders", "spirv-unknown-spv1.5")
        .print_metadata(MetadataPrintout::Full)
        .build() {
        Ok(_) => {}
        Err(e) => panic!("{}", e)
    }
}
```

## System Info

 - Rust: rustc 1.66.0-nightly (8ce3204af 2022-09-30)
 - OS: Arch Linux x86_64 6.0.7-zen1-1-zen
 - GPU: NVIDIA GeForce RTX 3080
 - SPIR-V: -

## Backtrace

<details><summary>Backtrace</summary>
<p>

```
# RUST_BACKTRACE=full cargo build

warning: `panic` setting is ignored for `test` profile
   Compiling project v0.1.0 (/path/to/project)
error: failed to run custom build command for `project v0.1.0 (/path/to/project)`

Caused by:
  process didn't exit successfully: `/path/to/project/target/debug/build/project-fd59eef972931d54/build-script-build` (exit status: 101)
  --- stderr
  warning: `panic` setting is ignored for `test` profile
     Compiling libm v0.2.6
     Compiling num-traits v0.2.15
  error: missing libm intrinsic _RNvNtNtCsdZLD7L8TQMH_4libm4math4rint4rint, which is math::rint::rint

  error: could not compile `libm` due to previous error
  warning: build failed, waiting for other jobs to finish...
  thread 'main' panicked at 'Build failed', build.rs:8:19
  stack backtrace:
     0:     0x5621e1952e30 - std::backtrace_rs::backtrace::libunwind::trace::h48a6b877947e3b61
                                 at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
     1:     0x5621e1952e30 - std::backtrace_rs::backtrace::trace_unsynchronized::hfe09011594941abe
                                 at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
     2:     0x5621e1952e30 - std::sys_common::backtrace::_print_fmt::h9ce2ad36264dcd3e
                                 at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/std/src/sys_common/backtrace.rs:66:5
     3:     0x5621e1952e30 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h4f730349406daa4f
                                 at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/std/src/sys_common/backtrace.rs:45:22
     4:     0x5621e1974bde - core::fmt::write::h4545826f01b877ac
                                 at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/core/src/fmt/mod.rs:1209:17
     5:     0x5621e194f915 - std::io::Write::write_fmt::hac4d3a613c78c8e4
                                 at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/std/src/io/mod.rs:1679:15
     6:     0x5621e1954cc3 - std::sys_common::backtrace::_print::ha560f7b733dc8a6e
                                 at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/std/src/sys_common/backtrace.rs:48:5
     7:     0x5621e1954cc3 - std::sys_common::backtrace::print::hcca78599db59c8b4
                                 at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/std/src/sys_common/backtrace.rs:35:9
     8:     0x5621e1954cc3 - std::panicking::default_hook::{{closure}}::h0d6a74e6cb8499ce
                                 at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/std/src/panicking.rs:267:22
     9:     0x5621e195499a - std::panicking::default_hook::hcb5d3609ae810fb1
                                 at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/std/src/panicking.rs:286:9
    10:     0x5621e1955369 - std::panicking::rust_panic_with_hook::h4f2461a1c1c1a86e
                                 at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/std/src/panicking.rs:669:13
    11:     0x5621e1955267 - std::panicking::begin_panic_handler::{{closure}}::hcad64e5dfff8b9ed
                                 at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/std/src/panicking.rs:560:13
    12:     0x5621e19532dc - std::sys_common::backtrace::__rust_end_short_backtrace::h2a66b4ccd8d28c5b
                                 at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/std/src/sys_common/backtrace.rs:138:18
    13:     0x5621e1954f82 - rust_begin_unwind
                                 at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/std/src/panicking.rs:556:5
    14:     0x5621e191c023 - core::panicking::panic_fmt::h443d402932f5c508
                                 at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/core/src/panicking.rs:142:14
    15:     0x5621e191c858 - core::panicking::panic_display::hcc3eb1790cbb9924
                                 at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/core/src/panicking.rs:72:5
    16:     0x5621e191c978 - build_script_build::main::h494e98762ca1e72e
                                 at /path/to/project/build.rs:8:19
    17:     0x5621e191c723 - core::ops::function::FnOnce::call_once::h64d912e98fe37cc1
                                 at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/core/src/ops/function.rs:251:5
    18:     0x5621e191c723 - std::sys_common::backtrace::__rust_begin_short_backtrace::hfb131dbe312a3347
                                 at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/std/src/sys_common/backtrace.rs:122:18
    19:     0x5621e191c9f9 - std::rt::lang_start::{{closure}}::h5a65321c29078a5b
                                 at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/std/src/rt.rs:166:18
    20:     0x5621e194ca8f - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hf4213b554e8bd1a4
                                 at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/core/src/ops/function.rs:286:13
    21:     0x5621e194ca8f - std::panicking::try::do_call::hc3fbf4159b659139
                                 at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/std/src/panicking.rs:464:40
    22:     0x5621e194ca8f - std::panicking::try::h257df37bf4b12652
                                 at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/std/src/panicking.rs:428:19
    23:     0x5621e194ca8f - std::panic::catch_unwind::h32410c5e0bc1d9b7
                                 at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/std/src/panic.rs:137:14
    24:     0x5621e194ca8f - std::rt::lang_start_internal::{{closure}}::he219927783e71113
                                 at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/std/src/rt.rs:148:48
    25:     0x5621e194ca8f - std::panicking::try::do_call::hb16738ddaef29072
                                 at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/std/src/panicking.rs:464:40
    26:     0x5621e194ca8f - std::panicking::try::hea0e210dc740f24b
                                 at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/std/src/panicking.rs:428:19
    27:     0x5621e194ca8f - std::panic::catch_unwind::hf267664358c36fa0
                                 at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/std/src/panic.rs:137:14
    28:     0x5621e194ca8f - std::rt::lang_start_internal::h778c8391ec5ee32b
                                 at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/std/src/rt.rs:148:20
    29:     0x5621e191c9df - main
    30:     0x7f1e724f2290 - <unknown>
    31:     0x7f1e724f234a - __libc_start_main
    32:     0x5621e191c2a5 - _start
                                 at /build/glibc/src/glibc/csu/../sysdeps/x86_64/start.S:115
    33:                0x0 - <unknown>
FAIL: 101
```

</p>
</details>

**Comment by charles-r-earp** [comment]
It looks like libm was updated recently. https://crates.io/crates/libm/versions
Reverting to the previous version fixed the issue for me. 

Add a patch section the shader Cargo.toml:
    
    [patch.crates-io]
    libm = { git = "https://github.com/rust-lang/libm", tag = "0.2.5" }

Then you have to update the lock file ie `cargo update`.
