### ISSUE TITLE
`error: u64 without OpCapability Int64` while compiling shader crate

### ISSUE THREAD

**Issue by bits0rcerer** [EmbarkStudios/rust-gpu#939]
### Expected Behaviour
Shader crate compiles successfully

### Example & Steps To Reproduce

1. create shader crate with following shader

<details><summary>Shader/lib.rs</summary>

```rust
#![cfg_attr(target_arch = "spirv", no_std)]
#![allow(arithmetic_overflow)]
// HACK(eddyb) can't easily see warnings otherwise from `spirv-builder` builds.
#![deny(warnings)]

use glam::UVec3;
use spirv_std::{glam, spirv};

#[derive(Copy, Clone)]
pub struct RandomSpreadStructurePlacementParameter {
    spacing: i32,
    separation: i32,
    salt: i32,
}

#[derive(Copy, Clone)]
pub struct KnownStructure {
    x: i32,
    z: i32,
    placement_params_index: u32,
}

const SENTINEL_NO_FEATURE_CHUNK: i64 = -1i64;

#[spirv(compute(threads(64, 9)))]
pub fn cs_main(
    #[spirv(global_invocation_id)] id: UVec3,
    #[spirv(uniform, descriptor_set = 0, binding = 0)] placement_params: &[RandomSpreadStructurePlacementParameter],
    #[spirv(uniform, descriptor_set = 0, binding = 1)] known_structures: &[KnownStructure],
    #[spirv(storage_buffer, descriptor_set = 0, binding = 2)] storage: &mut [i64],
) {
    let known_struct = known_structures[id.y as usize];
    let placement = placement_params[known_struct.placement_params_index as usize];
    let seed = storage[id.x as usize];

    if !is_feature_chunk_position(placement, seed, known_struct.x, known_struct.z) {
        storage[id.x as usize] = SENTINEL_NO_FEATURE_CHUNK;
    }
}

fn is_feature_chunk_position(params: RandomSpreadStructurePlacementParameter, seed: i64, x: i32, z: i32) -> bool {
    let x0 = floor_div(x, params.spacing);
    let z0 = floor_div(z, params.spacing);
    let mut r = LegacyRandom::with_large_feature_seed_and_salt(seed, x0, z0, params.salt);

    let x_spread = r.next_int_bound(params.spacing - params.separation);
    let z_spread = r.next_int_bound(params.spacing - params.separation);

    x0 * params.spacing + x_spread == x && z0 * params.spacing + z_spread == z
}

fn floor_div(x: i32, y: i32) -> i32 {
    let r = x / y;
    // if the signs are different and modulo not zero, round down
    if (x ^ y) < 0 && (r * y != x) {
        return r - 1;
    }
    return r;
}

struct LegacyRandom {
    state: i64,
}

const MODULUS_MASK: i64 = 281474976710655i64;
const MULTIPLIER: i64 = 25214903917i64;
const INCREMENT: i64 = 11i64;

impl LegacyRandom {
    fn with_large_feature_seed_and_salt(seed: i64, x: i32, z: i32, salt: i32) -> LegacyRandom {
        LegacyRandom {
            state: (seed as i64) + (salt as i64) + ((x as i64) * 341873128712i64) + ((z as i64) * 132897987541i64)
        }
    }

    fn next_int_bound(&mut self, bound: i32) -> i32 {
        return if (bound & bound - 1) == 0 {
            ((bound as i64) * (self.next(31) as i64) >> 31) as i32
        } else {
            let mut i: i32;
            let mut j: i32;

            loop {
                i = self.next(31);
                j = i % bound;

                if !((i - j + bound - 1) < 0) {
                    break;
                }
            }

            j
        };
    }

    fn next(&mut self, bits: i32) -> i32 {
        self.state = ((self.state * MULTIPLIER) + INCREMENT) & MODULUS_MASK;
        (self.state >> (48 - bits)) as i32
    }
}
```

</details>

<details><summary>build.rs</summary>

```rust
use spirv_builder::{MetadataPrintout, SpirvBuilder};

fn main() {
    match SpirvBuilder::new("shaders", "spirv-unknown-spv1.5")
        .print_metadata(MetadataPrintout::Full)
        .build() {
        Ok(_) => {}
        Err(e) => panic!("{}", e)
    }
}
```

</details>

2. compile project with `cargo build` (shader crate compiles using [spirv-builder](https://embarkstudios.github.io/rust-gpu/book/writing-shader-crates.html#using-spirv-builder))
3. see error `error: u64 without OpCapability Int64`

## System Info

 - Rust: rustc 1.66.0-nightly (8ce3204af 2022-09-30)
 - OS: Arch Linux x86_64 6.0.7-zen1-1-zen
 - GPU: NVIDIA GeForce RTX 3080

## Backtrace

<details><summary>Backtrace</summary>
<p>

```
$ RUST_BACKTRACE=full cargo build 

error: failed to run custom build command for `project v0.1.0 (/path/to/project)`

Caused by:
  process didn't exit successfully: `/path/to/project/target/debug/build/project-f842b42cbc9f0103/build-script-build` (exit status: 101)
  --- stderr
  warning: `panic` setting is ignored for `test` profile
     Compiling linear_random_structure_placement v0.1.0 (/path/to/project/shaders/shader_crate)
  error: u64 without OpCapability Int64
     --> /home/user/.rustup/toolchains/nightly-2022-10-01-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:487:1
      |
  487 | pub unsafe fn drop_in_place<T: ?Sized>(to_drop: *mut T) {
      | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      |
      = note: Stack:

  error: u64 without OpCapability Int64
     --> /home/user/.rustup/toolchains/nightly-2022-10-01-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:487:1
      |
  487 | pub unsafe fn drop_in_place<T: ?Sized>(to_drop: *mut T) {
      | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      |
      = note: Stack:
              cs_main

  error: No OpEntryPoint instruction was found. This is only allowed if the Linkage capability is being used.
    |
    = note: module `/path/to/project/target/spirv-builder/spirv-unknown-vulkan1.2/release/deps/linear_random_structure_placement.spv.dir/module`

  warning: an unknown error occurred
    |
    = note: spirv-opt failed, leaving as unoptimized
    = note: module `/path/to/project/target/spirv-builder/spirv-unknown-vulkan1.2/release/deps/linear_random_structure_placement.spv.dir/module`

  error: error:0:0 - No OpEntryPoint instruction was found. This is only allowed if the Linkage capability is being used.
    |
    = note: spirv-val failed
    = note: module `/path/to/project/target/spirv-builder/spirv-unknown-vulkan1.2/release/deps/linear_random_structure_placement.spv.dir/module`

  warning: `linear_random_structure_placement` (lib) generated 1 warning
  error: could not compile `linear_random_structure_placement` due to 4 previous errors; 1 warning emitted
  thread 'main' panicked at 'Build failed', build.rs:8:19
  stack backtrace:
     0:     0x55643f387e30 - std::backtrace_rs::backtrace::libunwind::trace::h48a6b877947e3b61
                                 at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
     1:     0x55643f387e30 - std::backtrace_rs::backtrace::trace_unsynchronized::hfe09011594941abe
                                 at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
     2:     0x55643f387e30 - std::sys_common::backtrace::_print_fmt::h9ce2ad36264dcd3e
                                 at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/std/src/sys_common/backtrace.rs:66:5
     3:     0x55643f387e30 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h4f730349406daa4f
                                 at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/std/src/sys_common/backtrace.rs:45:22
     4:     0x55643f3a9bde - core::fmt::write::h4545826f01b877ac
                                 at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/core/src/fmt/mod.rs:1209:17
     5:     0x55643f384915 - std::io::Write::write_fmt::hac4d3a613c78c8e4
                                 at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/std/src/io/mod.rs:1679:15
     6:     0x55643f389cc3 - std::sys_common::backtrace::_print::ha560f7b733dc8a6e
                                 at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/std/src/sys_common/backtrace.rs:48:5
     7:     0x55643f389cc3 - std::sys_common::backtrace::print::hcca78599db59c8b4
                                 at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/std/src/sys_common/backtrace.rs:35:9
     8:     0x55643f389cc3 - std::panicking::default_hook::{{closure}}::h0d6a74e6cb8499ce
                                 at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/std/src/panicking.rs:267:22
     9:     0x55643f38999a - std::panicking::default_hook::hcb5d3609ae810fb1
                                 at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/std/src/panicking.rs:286:9
    10:     0x55643f38a369 - std::panicking::rust_panic_with_hook::h4f2461a1c1c1a86e
                                 at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/std/src/panicking.rs:669:13
    11:     0x55643f38a267 - std::panicking::begin_panic_handler::{{closure}}::hcad64e5dfff8b9ed
                                 at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/std/src/panicking.rs:560:13
    12:     0x55643f3882dc - std::sys_common::backtrace::__rust_end_short_backtrace::h2a66b4ccd8d28c5b
                                 at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/std/src/sys_common/backtrace.rs:138:18
    13:     0x55643f389f82 - rust_begin_unwind
                                 at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/std/src/panicking.rs:556:5
    14:     0x55643f351e13 - core::panicking::panic_fmt::h443d402932f5c508
                                 at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/core/src/panicking.rs:142:14
    15:     0x55643f352678 - core::panicking::panic_display::h480338f3291023a4
    16:     0x55643f35279f - build_script_build::main::h384a7aff7fdda3d6
    17:     0x55643f352373 - std::sys_common::backtrace::__rust_begin_short_backtrace::ha7a0e95ad85b051c
    18:     0x55643f352389 - std::rt::lang_start::{{closure}}::h2205f383102920b7
    19:     0x55643f381a8f - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hf4213b554e8bd1a4
                                 at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/core/src/ops/function.rs:286:13
    20:     0x55643f381a8f - std::panicking::try::do_call::hc3fbf4159b659139
                                 at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/std/src/panicking.rs:464:40
    21:     0x55643f381a8f - std::panicking::try::h257df37bf4b12652
                                 at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/std/src/panicking.rs:428:19
    22:     0x55643f381a8f - std::panic::catch_unwind::h32410c5e0bc1d9b7
                                 at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/std/src/panic.rs:137:14
    23:     0x55643f381a8f - std::rt::lang_start_internal::{{closure}}::he219927783e71113
                                 at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/std/src/rt.rs:148:48
    24:     0x55643f381a8f - std::panicking::try::do_call::hb16738ddaef29072
                                 at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/std/src/panicking.rs:464:40
    25:     0x55643f381a8f - std::panicking::try::hea0e210dc740f24b
                                 at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/std/src/panicking.rs:428:19
    26:     0x55643f381a8f - std::panic::catch_unwind::hf267664358c36fa0
                                 at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/std/src/panic.rs:137:14
    27:     0x55643f381a8f - std::rt::lang_start_internal::h778c8391ec5ee32b
                                 at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/std/src/rt.rs:148:20
    28:     0x55643f352808 - main
    29:     0x7f8520c54290 - <unknown>
    30:     0x7f8520c5434a - __libc_start_main
    31:     0x55643f352095 - _start
                                 at /build/glibc/src/glibc/csu/../sysdeps/x86_64/start.S:115
    32:                0x0 - <unknown>
FAIL: 101
```

</p>
</details>

**Comment by bits0rcerer** [comment]
A bit diving through the code I found my error message [here](https://github.com/EmbarkStudios/rust-gpu/blob/7e83721978ccfb9132e6de262c6e1789811cfb4d/crates/rustc_codegen_spirv/src/spirv_type.rs#L117).

So I think I have to make sure the compiler knows I want to use the [Int64 Capability](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#Capability). As far as I understand the specification the compiler has to include the spirv asm line `OpCapability Int64`.

So the main question is: How do I do this?

**Comment by Patryk27** [comment]
When calling `SpirvBuilder`, add:
```
.capability(Capability::Int64)
```
